# Licensed under The Unlicense
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      
      - name: General
        uses: lowlighter/metrics@latest
        with:
          # GitHub token
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, achievements, calendar
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, deployer, member
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_calendar: true
          plugin_calendar_limit: n == 0
          
