# Licensed under The Unlicense
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: sgm17
          template: classic
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, achievements, activity
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          
